name: ytehaiduong
version: 1.0.0+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  google_fonts:
  cupertino_icons: ^1.0.2
  get:
  logging:
  intl:
  get_storage:
  dio:
  dio_smart_retry: ^1.2.0
  url_launcher:
  connectivity_plus:
  local_auth:
  image_picker:
  cached_network_image:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/audios/
